AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM Cloudformation template"

Resources:
    # IAM User GurnikCFN
    MyIAMUser: 
        Type: "AWS::IAM::User"
        Properties: 
            UserName: "GurnikCFN"
    
    # IAM Group "developer"
    MyIAMGroup:
        Type: "AWS::IAM::Group"
        Properties: 
            GroupName: "developer"

    # Add Users to IAM Group "developer"
    MyIAMUserToGroupAddition:
        Type: "AWS::IAM::UserToGroupAddition"
        Properties: 
            GroupName: !Ref "MyIAMGroup"
            Users: 
                -   !Ref "MyIAMUser"
    
    # IAM Role 
    MyIAMRole: 
        Type: 'AWS::IAM::Role'
        Properties: 
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement:
                    -   Effect: "Allow"
                        Principal: 
                            Service: ["ec2.amazonaws.com"]
                        Action: ["sts:AssumeRole"]
            ManagedPolicyArns: 
                -   "arn:aws:iam::aws:policy/PowerUserAccess"
    
    # IAM Policy "CustomPolicy"
    MyIAMPolicy:
        Type: "AWS::IAM::Policy"
        Properties: 
            PolicyName: "CustomPolicy"
            PolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                    -   Effect: "Allow"
                        Action:
                            -   "s3:GetObject"
                        Resource: "*"
            Roles: 
            -   !Ref "MyIAMRole"
